### ISSUE TITLE
python function is failed to start

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh-worker-service#302]
## Reproduce:

1. Enable function api in sn-cloud

```bash
# get credentials for api service
# for example, if running with sncloud test:
# gcloud container clusters get-credentials api --region us-west1 --project sncloud-test
# edit the pulsarcluster
k -n ${ns} edit pulsarclusters.cloud.streamnative.io ${cluster} -o yaml
```

add `functionEnabled: true` to `.spec.config` to enable the functions feature.

2. Create a python function in sn-cloud

```
pulsarctl functions create --output output_topic --inputs input_topic --tenant public --namespace default --name excla --py exclamation.py --classname e
xclamation.ExclamationFunction
```

`exclamation.py`
```
/ # cat exclamation.py
from pulsar import Function

# The classic ExclamationFunction that appends an exclamation at the end
# of the input
class ExclamationFunction(Function):
  def __init__(self):
    pass

  def process(self, input, context):
    return input + '!'
```

3. Get logs of function pod

```
azureuser@pengcheng-dev:~$ kubectl logs excla-836244ef-function-0
W0708 02:35:40.630389  374206 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
"The package 'function://public/default/excla' downloaded to path 'download/pulsar_functions/exclamation.py' successfully"
shardId=0
[2022-07-08 02:34:38 +0000] [INFO] python_instance_main.py: Starting Python instance with Namespace(client_auth_params='{"audience":"urn:sn:pulsar:o-qcdne:my-instance","issuerUrl":"https://auth.test.cloud.gcp.streamnative.dev/","privateKey":"file:///mnt/secrets/broker_client_credential.json","type":"client_credentials"}', client_auth_plugin='org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2', cluster_name='my-pulsar1', dependency_repository=None, expected_healthcheck_interval=-1, extra_dependency_repository=None, function_details='{"tenant":"public","namespace":"default","name":"excla-836244ef","className":"exclamation.ExclamationFunction","userConfig":"{}","autoAck":true,"parallelism":1,"source":{"typeClassName":"[B","inputSpecs":{"input_topic":{}},"cleanupSubscription":true,"subscriptionPosition":"EARLIEST"},"sink":{"typeClassName":"[B","topic":"output_topic","producerSpec":{}},"resources":{"cpu":1,"ram":"1073741824"},"componentType":"FUNCTION"}', function_id='0-9ff921e2-aa97-4f03-885c-39f931da8c68', function_version='0', hostname_verification_enabled=None, install_usercode_dependencies=None, instance_id='0', logging_config_file='/pulsar/conf/functions-logging/console_logging_config.ini', logging_directory='logs/functions', logging_file='excla-836244ef-0', max_buffered_tuples='100', metrics_port=9094, port=9093, pulsar_serviceurl='pulsar://my-pulsar1-broker.o-qcdne.svc.cluster.local:6650', py='download/pulsar_functions/exclamation.py', secrets_provider=None, secrets_provider_config=None, state_storage_serviceurl=None, tls_allow_insecure_connection=None, tls_trust_cert_path=None, use_tls='false')
2022-07-08 02:34:38.395 ERROR [139681111017280] AuthOauth2:153 | Failed to initialize ClientCredentialFlow: issuer_url is not set
2022-07-08 02:34:38.397 INFO  [139681111017280] Client:88 | Subscribing on Topic :input_topic
2022-07-08 02:34:38.397 INFO  [139681044023040] ExecutorService:41 | Run io_service in a single thread
2022-07-08 02:34:38.397 INFO  [139681111017280] ClientConnection:189 | [<none> -> pulsar://my-pulsar1-broker.o-qcdne.svc.cluster.local:6650] Create ClientConnection, timeout=10000
2022-07-08 02:34:38.397 INFO  [139681111017280] ConnectionPool:96 | Created connection for pulsar://my-pulsar1-broker.o-qcdne.svc.cluster.local:6650
2022-07-08 02:34:38.398 INFO  [139681044023040] ClientConnection:375 | [10.32.21.102:58410 -> 10.36.4.33:6650] Connected to broker
2022-07-08 02:34:38.398 ERROR [139681044023040] ClientConnection:473 | [10.32.21.102:58410 -> 10.36.4.33:6650] Failed to establish connection: AuthenticationError
2022-07-08 02:34:38.398 INFO  [139681044023040] ClientConnection:1558 | [10.32.21.102:58410 -> 10.36.4.33:6650] Connection closed
2022-07-08 02:34:38.398 ERROR [139681044023040] ClientImpl:394 | Error Checking/Getting Partition Metadata while Subscribing on persistent://public/default/input_topic -- AuthenticationError
2022-07-08 02:34:38.399 INFO  [139681044023040] ClientConnection:263 | [10.32.21.102:58410 -> 10.36.4.33:6650] Destroyed connection
[2022-07-08 02:34:38 +0000] [ERROR] log.py: Traceback (most recent call last):
[2022-07-08 02:34:38 +0000] [ERROR] log.py:   File "/pulsar/instances/python-instance/python_instance_main.py", line 218, in <module>
[2022-07-08 02:34:38 +0000] [ERROR] log.py: main()
[2022-07-08 02:34:38 +0000] [ERROR] log.py:   File "/pulsar/instances/python-instance/python_instance_main.py", line 199, in main
[2022-07-08 02:34:38 +0000] [ERROR] log.py: pyinstance.run()
[2022-07-08 02:34:38 +0000] [ERROR] log.py:   File "/pulsar/instances/python-instance/python_instance.py", line 191, in run
[2022-07-08 02:34:38 +0000] [ERROR] log.py: self.consumers[topic] = self.pulsar_client.subscribe(
[2022-07-08 02:34:38 +0000] [ERROR] log.py:   File "/pulsar/instances/python-instance/pulsar/__init__.py", line 748, in subscribe
[2022-07-08 02:34:38 +0000] [ERROR] log.py: c._consumer = self._client.subscribe(topic, subscription_name, conf)
[2022-07-08 02:34:38 +0000] [ERROR] log.py: _pulsar
[2022-07-08 02:34:38 +0000] [ERROR] log.py: .
[2022-07-08 02:34:38 +0000] [ERROR] log.py: AuthenticationError
[2022-07-08 02:34:38 +0000] [ERROR] log.py: :
[2022-07-08 02:34:38 +0000] [ERROR] log.py: Pulsar error: AuthenticationError
2022-07-08 02:34:38.406 INFO  [139681044023040] ExecutorService:47 | Event loop of ExecutorService exits successfully
```

**Comment by jiangpengcheng** [comment]
looks like the `/pulsar/instances/python-instance/python_instance_main.py` doesn't support oauth2 yet

**Comment by freeznet** [comment]
could you please paste the start command of the function container? the python instance should support oauth2 already.

**Comment by jiangpengcheng** [comment]
```
  pulsar-function:
    Container ID:  containerd://b4833703854a33a6bb69731a3d9c128a8db96761acbb0a546b5c1b4e491eafb4
    Image:         streamnative/pulsar-functions-python-runner:2.9.2.19
    Image ID:      docker.io/streamnative/pulsar-functions-python-runner@sha256:9d173581bf4ff21196fa5df3773083db5dc4b652786591fd6b986d027e5067bd
    Ports:         9093/TCP, 9094/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      sh
      -c
      /pulsar/bin/pulsar-admin --admin-url $webServiceURL --auth-plugin $clientAuthenticationPlugin --auth-params $clientAuthenticationParameters packages download function://public/default/excla --path download/pulsar_functions/exclamation.py && SHARD_ID=${POD_NAME##*-} && echo shardId=${SHARD_ID} && exec python /pulsar/instances/python-instance/python_instance_main.py --py download/pulsar_functions/exclamation.py --logging_directory logs/functions --logging_file excla-836244ef-${SHARD_ID} --logging_config_file /pulsar/conf/functions-logging/console_logging_config.ini --instance_id ${SHARD_ID} --function_id ${SHARD_ID}-9ff921e2-aa97-4f03-885c-39f931da8c68 --function_version 0 --function_details '{"tenant":"public","namespace":"default","name":"excla-836244ef","className":"exclamation.ExclamationFunction","userConfig":"{}","autoAck":true,"parallelism":1,"source":{"typeClassName":"[B","inputSpecs":{"input_topic":{}},"cleanupSubscription":true,"subscriptionPosition":"EARLIEST"},"sink":{"typeClassName":"[B","topic":"output_topic","producerSpec":{}},"resources":{"cpu":1,"ram":"1073741824"},"componentType":"FUNCTION"}' --pulsar_serviceurl $brokerServiceURL --max_buffered_tuples 100 --port 9093 --metrics_port 9094 --expected_healthcheck_interval -1 --cluster_name my-pulsar1 --client_auth_plugin $clientAuthenticationPlugin --client_auth_params $clientAuthenticationParameters --use_tls false
    State:          Waiting
      Reason:       CrashLoopBackOff
```

**Comment by jiangpengcheng** [comment]
![image](https://user-images.githubusercontent.com/1858477/177925147-906b7b73-aaf4-4087-bd49-274d11cf72a2.png)

**Comment by jiangpengcheng** [comment]
or caused by the `use_tls false`?

**Comment by freeznet** [comment]
seems related to https://github.com/apache/pulsar/blob/branch-2.10/pulsar-client-cpp/lib/auth/AuthOauth2.cc#L140-L144
the CPP uses `issuer_url` as the JSON key, and the provided auth params are using `issuerUrl`

**Comment by jiangpengcheng** [comment]
then I think it's better to unify the format for all languages

**Comment by freeznet** [comment]
after sync with @jiangpengcheng, it could be fixed in mesh worker service, by convert the `clientAuthenticationParameters` to `UnderScoreCase` for python functions in `KubernetesUtils.buildAuthConfigMap`
