### ISSUE TITLE
[bug] function list get `field label not supported` error

### ISSUE THREAD

**Issue by nlu90** [streamnative/function-mesh-worker-service#743]
```
pulsar-broker 2023-05-04T20:21:48,320+0000 [pulsar-web-37-3] ERROR io.functionmesh.compute.rest.api.MeshComponentImpl - failed to fetch functions list from namespace functionsnamespace
pulsar-broker org.apache.pulsar.common.util.RestException: failed to perform the request: responseCode: 400, responseMessage: , responseBody: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","mes
sage":"field label not supported: compute.functionmesh.io/pulsar-cluster","reason":"BadRequest","code":400}
pulsar-broker
pulsar-broker     at io.functionmesh.compute.rest.api.MeshComponentImpl.executeCall(MeshComponentImpl.java:215) ~[?:?]
pulsar-broker     at io.functionmesh.compute.rest.api.MeshComponentImpl.listFunctions(MeshComponentImpl.java:380) ~[?:?]
pulsar-broker     at io.functionmesh.compute.rest.api.FunctionsImpl.listFunctions(FunctionsImpl.java:825) ~[?:?]
pulsar-broker     at org.apache.pulsar.broker.admin.impl.FunctionsBase.listFunctions(FunctionsBase.java:485) ~[io.streamnative-pulsar-broker-2.10.4.1.jar:2.10.4.1]
pulsar-broker     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
pulsar-broker     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
pulsar-broker     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
pulsar-broker     at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
pulsar-broker     at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~
```

The cause for this error is that the Kubernetes java client version upgrade from `12.0.2` to `18.0.0`.

The method signature for list functions are changed:

```
// 12.0.2
public okhttp3.Call listNamespacedCustomObjectCall(
String group,
String version,
String namespace,
String plural,
String pretty,
String _continue,
String fieldSelector,
String labelSelector,
Integer limit,
String resourceVersion,
Integer timeoutSeconds,
Boolean watch,
final ApiCallback _callback)

// 18.0.0
public okhttp3.Call listNamespacedCustomObjectCall(
String group,
String version,
String namespace,
String plural,
String pretty,
Boolean allowWatchBookmarks,
String _continue,
String fieldSelector,
String labelSelector,
Integer limit,
String resourceVersion,
String resourceVersionMatch,
Integer timeoutSeconds,
Boolean watch,
final ApiCallback _callback)
```

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/16407807/236331726-38e834bf-5d78-4b1a-81eb-aa5aded57f17.png">

Notice the new `Boolean allowWatchBookmarks` added ahead of `labelSelector`; this causes the labels intended for `labelSelector` to be passed to `fieldSelector.`

**Comment by nlu90** [comment]
The commit hash for the change is: 35a013c1bc439c7836f31ac94cbf4864eb8086b1
And affect branches are: 
```
HEAD
branch-2.10.4.1
origin/branch-2.10.4
origin/branch-2.10.4.1
origin/upgrade-version
```
